### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by zjsxfly** [TencentWecom/wecom-cloudbase-framework-template-vue#1]
云环境是新创建的，以下是log错误部分提示：
$ docker rm -f e5c5ea803a4c4bdb0667c099de3c0d274f36cfa1f4c3307dc3e8fca29003eae6
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by gzzhanghao** [comment]
在填写 `WECOM_CUSTOM_LOGIN_PRIVATE_KEY` 的时候需要把 `private_key` 中的 `\n` 替换成 `\\n`，是不是漏掉了这一步？

**Comment by zjsxfly** [comment]
是这个原因，谢谢
